name: Auto PR from dev1 to main
on:
  push:
    branches:
      - dev1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev1 branch
        uses: actions/checkout@v4
        with:
          ref: dev1

      - name: Create PR to main
        uses: repo-sync/pull-request@v5
        with:
          source_branch: dev1
          destination_branch: main
          pr_title: "Auto PR: Merge dev1 into main"
          pr_body: "This PR was created automatically by GitHub Actions."
          github_token: ${{ secrets.GITHUB_TOKEN }}

          
