name: AutoMergeToMain

on:
  push:
    branches:
      - dev1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev1 branch
        uses: actions/checkout@v4
        with:
          ref: dev1
          fetch-depth: 0

      - name: Create PR from dev1 to main
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: dev1
          destination_branch: main
          pr_title: "Auto PR: Merge dev1 into main"
          pr_body: "This PR was created automatically by GitHub Actions."

      # - name: Enable auto-merge on PR
      #   if: steps.create_pr.outputs.pr_number != ''
      #   run: |
      #     echo "Enabling auto-merge for PR #${{ steps.create_pr.outputs.pr_number }}"
      #     gh pr merge ${{ steps.create_pr.outputs.pr_number }} --auto --merge
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          # added one line of code
