name: AutoMergeToMain

on:
  push:
    branches:
      - uat1
    paths:
      - '.github/workflows/AutoMerge.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev1 branch
        uses: actions/checkout@v4
        with:
          ref: uat1
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name 'Sreenivas0906'
          git config --global user.email 'sreenuk0906@gmail.com'

      - name: Create PR from uat1 to main
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: uat1
          destination_branch: main
          pr_title: "Auto PR: Merge uat1 into main"
          pr_body: "This PR was created automatically by GitHub Actions."

      - name: Get PR number
        id: get_pr_number
        run: |
            PR_NUMBER=$(gh pr list --head uat --base main --json number -q '.[0].number')
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Check if PR is mergeable and enable auto-merge
        run: |
            gh pr merge ${{ steps.get_pr_number.outputs.pr_number }} --auto --merge
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


            # added a single line for testing purpose
            # added a single line for testing purpose
            # added a single line for testing purpose