name: AutoMergeToMain

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch name
        id: vars
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Set up GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request with GitHub CLI
        id: create_pr
        run: |
          echo "Creating PR from ${{ steps.vars.outputs.branch_name }} to main..."
          gh pr create --base main --head ${{ steps.vars.outputs.branch_name }} \
            --title "Auto PR: Merge ${{ steps.vars.outputs.branch_name }} to main" \
            --body "Automatically created PR from branch to main." || echo "PR may already exist."

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: |
          pr_number=$(gh pr list --head ${{ steps.vars.outputs.branch_name }} --json number -q '.[0].number')
          if [[ -n "$pr_number" ]]; then
            echo "Merging PR #$pr_number..."
            gh pr merge $pr_number --merge --admin
          else
            echo "No PR found to merge."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
