name: AutoMergeToMain

on:
  push:
    branches:
      - test1603
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev1 branch
        uses: actions/checkout@v4
        with:
          ref: dev1

      - name: Create PR from dev1 to main
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: test1603
          destination_branch: main
          pr_title: "Auto PR: Merge dev1 into main"
          pr_body: "This PR was created automatically by GitHub Actions."

      - name: Auto merge the pull request
        if: steps.create_pr.outputs.pr_number != ''
        run: |
          echo "PR number is: ${{ steps.create_pr.outputs.pr_number }}"
          gh pr merge ${{ steps.create_pr.outputs.pr_number }} --merge --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# added a new line
# added a second line