name: AutoMergeToMain

on:
  push:
    branches:
      - uat
    paths:
      - '.github/workflows/AutoMerge.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev1 branch
        uses: actions/checkout@v4
        with:
          ref: uat
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name 'Sreenivas0906'
          git config --global user.email 'sreenuk0906@gmail.com'

      - name: Create PR from uat to main
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: uat
          destination_branch: main
          pr_title: "Auto PR: Merge uat into main"
          pr_body: "This PR was created automatically by GitHub Actions."

          # added one more line to check if the PR already exists

      # - name: Auto merge the pull request
      #   if: steps.create_pr.outputs.pr_number != ''
      #   run: |
      #     echo "PR number is: ${{ steps.create_pr.outputs.pr_number }}"
      #     gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      #     gh pr merge ${{ steps.create_pr.outputs.pr_number }} --merge --admin
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}